### ISSUE TITLE
StyleCI for better Code-Style

### ISSUE THREAD

**Issue by Gummibeer** [maknz/slack#45]
@maknz cause of the fallen keyword "code-style" in PR #44 why not using StyleCI? https://styleci.io/
It's free for open source and also used by laravel core - a simple config could look like:
```yaml
preset: laravel

risky: false

linting: true
```

And you can enable auto PR & auto merge & disable CI - this will fix all CS issues in PRs on the fly and no one has to care about CodeStyle.
